version: 43
jobs:
- name: onedev-repo-sync
  steps:
  - type: PushRepository
    name: Onedev-Nixos-Flake
    remoteUrl: https://github.com/TheZombie1999/Onedev-Nixos-Flake.git
    userName: TheZombie1999
    passwordSecret: Github
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
